version: '3'
services:
  postgres:
    container_name: test.db.postgres
    image: "postgres:10"
    ports:
      - "5432:5432"
    env_file:
      - .pg-variables.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data